### ISSUE TITLE
Clicking on "Open in Builder" from settings page does not respect the HTTP_BASE_URL

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza-webapp-admin#129]
**Describe the bug**
Opening builder does not use `HTTP_BASE_URL`
**To Reproduce**
Set up an instance with  `HTTP_BASE_URL` set to a non default value
Go to settings, list workflows, edit workflow, click on open builder

**Expected behavior**
It opens the builder using the correct url including the `HTTP_BASE_URL`

**Screenshots**
![image](https://user-images.githubusercontent.com/19151369/191586727-8aad4fb5-8fda-4ba4-85b7-8ddeebdaca6d.png)

*Additional Context*
This seems to be the guilty function

https://github.com/cortezaproject/corteza-webapp-admin/blob/8f162269f195fe582225bb9b908000b2b68b8947/src/components/Workflow/CWorkflowEditorInfo.vue#L210

**Comment by Fajfa** [comment]
Thank you for raising this issue, will be fixed in the upcoming 2022.9 release

**Comment by Fajfa** [comment]
https://github.com/cortezaproject/corteza-webapp-admin/commit/616ea53c70dafa4dbca6893e7cfb1d5ca3dd2a43
