### ISSUE TITLE
Don't make component mutate prop directly

### ISSUE THREAD

**Issue by tjerman** [cortezaproject/corteza-webapp-admin#14]
https://github.com/cortezaproject/corteza-webapp-admin/pull/12/commits/e55aecc08993a04ab7afca44283c3f2b9cc93967#diff-5e3683de41cf0ed2648c7fa5b3532f75R30

The method in question mutates the prop directly -- bad practice and should be refactored.

**Comment by darh** [comment]
If I understand this correctly, it's no longer an issue.
